# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0003_auto_20171113_1801'),
        ('jukebox', '0003_auto_20171117_0030'),
    ]

    operations = [
    ]
