# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 03:22


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0004_merge_20171117_0127'),
        ('jukebox', '0004_merge_20171118_0148'),
    ]

    operations = [
    ]
